repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
        name: "Check: no merge conflict strings"
#      - id: no-commit-to-branch
#        name: "Check: no commit to main"
#        args: [ --branch, main, --branch, master ]
#        stages: [ commit-msg ]
      - id: check-ast
        name: "Check: parse .py files"
        language_version: python3.12
      - id: check-json
        name: "Check: parse .json files"
      - id: check-toml
        name: "Check: parse .toml files"
      - id: check-yaml
        name: "Check: parse .yaml files"
      - id: check-case-conflict
        name: "Check: no case conflicting file names"
      - id: trailing-whitespace
        name: "Lint : remove trailing whitespaces"
      - id: end-of-file-fixer
        name: "Lint : files end with only newline"
      - id: mixed-line-ending
        name: "Lint : consistent file ending"
      - id: detect-private-key
        name: "Check: no private keys are commited"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.10
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
