services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    profiles: [ "prod" ]
    container_name: app_container
    environment:
      CONFIG__MODE: PROD
      CONFIG__DB__NAME: ${CONFIG__DB__NAME}
      CONFIG__DB__PASSWORD: ${CONFIG__DB__PASSWORD}
      CONFIG__DB__USER: ${CONFIG__DB__USER}
      CONFIG__DB__HOST: pg
      CONFIG__DB__PORT: ${CONFIG__DB__PORT}
      CONFIG__DB__DRIVER: ${CONFIG__DB__DRIVER}

      CONFIG__DB__ECHO: ${CONFIG__DB__ECHO}
      CONFIG__DB__ECHO_POOL: ${CONFIG__DB__ECHO_POOL}
      CONFIG__DB__POOL_SIZE: ${CONFIG__DB__POOL_SIZE}
      CONFIG__DB__MAX_OVERFLOW: ${CONFIG__DB__MAX_OVERFLOW}

      CONFIG__LOGGING__LEVEL: INFO
    ports:
      - "8000:8000"
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: postgres:16
    profiles: [ "prod" ]
    container_name: pg_container
    environment:
      POSTGRES_DB: ${CONFIG__DB__NAME}
      POSTGRES_USER: ${CONFIG__DB__USER}
      POSTGRES_PASSWORD: ${CONFIG__DB__PASSWORD}
    ports:
      - ${CONFIG__DB__PORT}:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 3s
      retries: 3

  pg_test:
    image: postgres:16
    profiles: [ "test" ]
    container_name: test_pg_container
    environment:
      POSTGRES_DB: ${CONFIG__TEST__DB__NAME}
      POSTGRES_USER: ${CONFIG__TEST__DB__USER}
      POSTGRES_PASSWORD: ${CONFIG__TEST__DB__PASSWORD}
    ports:
      - ${CONFIG__TEST__DB__PORT}:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 3s
      timeout: 3s
      retries: 3

volumes:
  pg_data:
