#!/usr/bin/env python3

from src.config import settings
from src.core.gunicorn import Application
from src.core.gunicorn.logger import GunicornLogger
from src.main import app as fastapi_app


def run_gunicorn():
    Application(
        app=fastapi_app,
        options={
            "bind": f"{settings.gunicorn.host}:{settings.gunicorn.port}",
            "timeout": settings.gunicorn.timeout,
            "workers": settings.gunicorn.workers,
            "worker_class": "uvicorn.workers.UvicornWorker",
            "loglevel": settings.logging.level,
            "logger_class": GunicornLogger,
            "accesslog": "-",
            "errorlog": "-",
        },
    ).run()


if __name__ == "__main__":
    run_gunicorn()
